name: cross-entropy-for-combinatorics
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.9.4
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - ase==3.21.1
    - chardet==4.0.0
    - cycler==0.10.0
    - decorator==4.4.2
    - googledrivedownloader==0.4
    - h5py==3.2.1
    - idna==2.10
    - isodate==0.6.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - networkx==2.5.1
    - numba==0.53.1
    - numpy==1.20.2
    - pandas==1.2.4
    - pillow==8.2.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-louvain==0.15
    - pytz==2021.1
    - rdflib==5.0.0
    - requests==2.25.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - six==1.15.0
    - threadpoolctl==2.1.0
    - torch==1.8.1
    - torch-geometric==1.7.0
    - torch-scatter==2.0.6
    - torchaudio==0.8.1
    - torchvision==0.9.1
    - tqdm==4.60.0
    - typing-extensions==3.10.0.0
    - urllib3==1.26.4
